name: "Feature request"
description: "Suggest an idea or enhancement for Structus"
title: "feat: <short description>"
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose an enhancement!

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see added/changed?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you considered.
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact / Compatibility
      description: Consider API impact, breaking changes, dependency policy, etc.
      placeholder: |
        - Public API changes:
        - Potential breaking change:
        - New dependencies:
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, examples, or extra details.
    validations:
      required: false
